In [6]:
import numpy
from crab.models import MatrixPreferenceDataModel
data = numpy.loadtxt(fname='test_recomon.csv', delimiter=',')

print data

ImportError: No module named models

In [3]:
from crab.models import MatrixPreferenceDataModel
m = MatrixPreferenceDataModel(data.data)
print m

ImportError: No module named models

In [9]:
print type(data)
print data.shape

<type 'numpy.ndarray'>
(400, 3)


In [10]:
print data[0:4, 0:3]

[[  1.  33.   1.]
 [  1.  39.   1.]
 [  1.   6.   1.]
 [  1.  26.   5.]]


In [11]:
print data.mean()

11.4625


In [12]:
print 'maximum inflammation:', data.max()
print 'minimum inflammation:', data.min()
print 'standard deviation:', data.std()

maximum inflammation: 40.0
minimum inflammation: 1.0
standard deviation: 10.5323435387


In [15]:
print data.mean(axis=0)

[ 10.5     20.9625   2.925 ]


In [18]:
import matplotlib.pyplot as plt

In [19]:
xs = [x for x in range(10)]
ys = [y*y for y in range(10)]
plt.plot(xs, ys)
plt.show()